local_costmap:
  # the coordinate frame that the local costmap should run in
  global_frame: odom
  # the coordinate frame for the base of the robot referenced by the local costmap
  robot_base_frame: robot_footprint
  # rate (in Hz) that local costmap runs its update loop
  update_frequency: 5.0
  # rate (in Hz) that local costmap publishes visualization information
  publish_frequency: 5.0

  # NOTE - the below parameters can be overwritten by some layers, namely the static map layer #
  # the width of the local costmap (in m)
  width: 10.0
  # the height of the local costmap (in m)
  height: 10.0
  # the resolution of the local costmap (in m/cell)
  resolution: 0.01
  # the x origin of the local costmap in the local frame (in m)
  origin_x: 0.0
  # the y origin of the local costmap in the local frame (in m)
  origin_y: 0.0

  # determines whether or not the local costmap should initialize itself based on a map served by map_server
  static_map: false
  # us a rolling window version of local costmap (if static map = true, this must be set to false)
  # rolling window means it is always centered at the robot
  rolling_window: true

  # padding space for the footprint of the robot
  footprint_padding: 0.0
